$(document).ready(function()
{
$('.header').hover(function(){
$('.panel').show();
});
$('#container').hover(function()
{
$('.panel').hide();
});
$('#login1').hover(function(){
$('#login1').css("background-color","grey");
},function(){$('#login1').css("background-color","white");});
$('#logo1').hover(function(){
$('#logo1').css("background-color","grey");
},function(){$('#logo1').css("background-color","white");});
$('#subjects1').hover(function(){
$('#subjects1').css("background-color","grey");
},function(){$('#subjects1').css("background-color","white");});
$('#about').hover(function(){
$('#about').css("background-color","grey");
},function(){$('#about').css("background-color","white");});
$('#notif').hover(function(){
$('#notif').css("background-color","grey");
},function(){$('#notif').css("background-color","white");});
$('#signup1').hover(function(){
$('#signup1').css("background-color","grey");
},function(){$('#signup1').css("background-color","white");});
$('#subjects1').click(function(){
$('.subindex').show();
});
$('#container').mouseover(function(){
$('.subindex').slideUp();
$('.subdesc').slideUp();
});
$('.content').mouseover(function(){
$('.subindex').slideUp();
$('.subdesc').slideUp();
});
$('#logo1').mouseover(function(){
$('.subindex').slideUp();
$('.subdesc').slideUp();
});
$('#about').mouseover(function(){
$('.subindex').slideUp();
$('.subdesc').slideUp();
});
$('#search').mouseover(function(){
$('.subindex').slideUp();
$('.subdesc').slideUp();
});
$('#notif').mouseover(function(){
$('.subindex').slideUp();
$('.subdesc').slideUp();
});
$('#login1').mouseover(function(){
$('.subindex').slideUp();
$('.subdesc').slideUp();
});
$('#signup1').mouseover(function(){
$('.subindex').slideUp();
$('.subdesc').slideUp();
});
$('#home').hover(function(){
$('#home').css("background-color","grey");
$('#home').css("color","black");
},function(){$('#home').css("background-color","white");
$('#home').css("color","grey");});
$('#databases').hover(function(){
$('#databases').css("background-color","grey");
$('#databases').css("color","black");
},function(){$('#databases').css("background-color","white");
$('#databases').css("color","grey");});
$('#webdevelopment').hover(function(){
$('#webdevelopment').css("background-color","grey");
$('#webdevelopment').css("color","black");
},function(){$('#webdevelopment').css("background-color","white");
$('#webdevelopment').css("color","grey");});
$('#bigdata').hover(function(){
$('#bigdata').css("background-color","grey");
$('#bigdata').css("color","black");
},function(){$('#bigdata').css("background-color","white");
$('#bigdata').css("color","grey");});
$('#cloudcomputing').hover(function(){
$('#cloudcomputing').css("background-color","grey");
$('#cloudcomputing').css("color","black");
},function(){$('#cloudcomputing').css("background-color","white");
$('#cloudcomputing').css("color","grey");});
$('#bi').hover(function(){
$('#bi').css("background-color","grey");
$('#bi').css("color","black");
},function(){$('#bi').css("background-color","white");
$('#bi').css("color","grey");});
$('#mobileanalytics').hover(function(){
$('#mobileanalytics').css("background-color","grey");
$('#mobileanalytics').css("color","black");
},function(){$('#mobileanalytics').css("background-color","white");
$('#mobileanalytics').css("color","grey");});

$('#signup1').click(function(){
$('.c').fadeIn();
$('.popup').fadeIn();
});
});